### ISSUE TITLE
When we use gcc to finish the compile,then we can run the component as this

### ISSUE THREAD

**Issue by lidanfeng** [DependableSystemsLab/LLFI#100]
When we use gcc to finish the compile,then we can run the component as this: dsware_osd -c /home/ds/script/config/dsware.cfg -s 6SL11RML0000N143CZBM -d /dev/sdb -f /dev/hiob -i 0 -p 1 > /home/ds/script/log/osd0.log 2>&1

But when we use clang finish the compile, we have to run the component as this , there is an error as follow:

**Comment by karthikp-ubc** [comment]
The error message is missing. Please provide more details along with a reproducible test case. Thanks,

- Karthik
