### ISSUE TITLE
which line of code it was injected to

### ISSUE THREAD

**Issue by lidanfeng** [DependableSystemsLab/LLFI#101]
We want to know the fault,for example “llfi-LowMemory(Res)”,which line of code it was injected to , is just injected to one place or multiple places?

   If the fault is injected in one place, why llfi choose this place; if the fault was injected to multiplace, why and how llfi choose these places?

**Comment by karthikp-ubc** [comment]
This is not an issue - please post this to the LLFI development list. The issue forum is not the appropriate place for posting questions related to LLFI. Thanks,

- Karthik
