### ISSUE TITLE
Did LLFI support LLVM-3.8.0 version？

### ISSUE THREAD

**Issue by zzh8845** [DependableSystemsLab/LLFI#102]
Did LLFI support LLVM-3.8.0 version？

If I install llfi already, can I change the llvm version?

PS:LLVM-3.4 is old,and some functions are not supported.

**Comment by nankmr2012** [comment]
LLFI does not support LLVM-3.8.0 version.
Also once LLFI installed with LLVM-3.4 version, the LLVM version cannot be changed.

**Comment by zzh8845** [comment]
Thanks

**Comment by junwei-wang** [comment]
How complicated to switch LLFI into latest LLVM versions?
