### ISSUE TITLE
Input corruption

### ISSUE THREAD

**Issue by Behroosh** [DependableSystemsLab/LLFI#104]
I have observed few cases where the input file is being modified/corrupted during a fault injection campaign. This invalidates the results of that campaign.
A solution to this could be to copy a clean version of the input file to the project directory for each experiment.

**Comment by karthikp-ubc** [comment]
Behrooz,

You mentioned you fixed this issue at your end. Would you mind submitting a PR with the same ?

Thanks,

- Karthik

**Comment by Behroosh** [comment]
I have not fixed this issue. However I have a suggestion on how one could fix this, and that is to copy a clean version of the input file to the project directory for each experiment so that if the input gets corrupted in one experiment, that would not affect the next experiment.
