### ISSUE TITLE
Python YAML Module Error

### ISSUE THREAD

**Issue by HamzaOmar** [DependableSystemsLab/LLFI#107]
Hi,

I am trying to install LLFi on my system via auto-installer but it keeps on giving me the error "ERROR: You need to install Python Yaml module before building LLFI." 
I tried installing the module of YAML on my own as well but still it gives me the error. Can you kindly help me out with this. 

Thanks.

**Comment by abrahamchan** [comment]
Hi Hamza,

Can you please check if your Python Yaml module is installed for Python 3 rather than Python 2, which is usually bundled with your Linux distribution?
