### ISSUE TITLE
Issue running the pass 

### ISSUE THREAD

**Issue by nezzariyasser** [DependableSystemsLab/LLFI#108]
I'm trying to run the pass but it shows the following error:
: undefined symbol: _ZTIN4llvm10ModulePassE
  -load request ignored.
Could you please help me solve it ?

**Comment by abrahamchan** [comment]
Hi there,

Thank you for using LLFI. Did you compile LLVM with RTTI enabled?

**Comment by karthikp-ubc** [comment]
Did this work for you ? If not, please let us know and reopen this thread. 

- Karthik

**Comment by nezzariyasser** [comment]
Dear Karthik,


Thank you very much for your reply, I just needed to include the input.yaml.


Regards, Yasser


________________________________
