### ISSUE TITLE
Installation Error

### ISSUE THREAD

**Issue by hakantekgul** [DependableSystemsLab/LLFI#111]
Hi,

I am using Mac OS X Mavericks and I am trying to install LLFI using command line. After it runs ./setup, I get the following error. Please help. I tried changing the ORACLE_JAVA_HOME and JAVA_HOME to /usr/libexec/java_home but it did not work. 

Running ./setup for LLFI:
-- Generating default software failures with /Users/hakantekgul/Desktop/LLFI/llfisrc/tools/FIDL/FIDL-Algorithm.py...
-- Success!
readlink: illegal option -- f
usage: readlink [-n] [file ...]

ERROR: Invalid ORACLE_JAVA_HOME: bin/javac not found!-- 

With regards, 
Hakan Tekgul
Electrical and Computer Engineering | Class of 2019
University of Illinois Urbana-Champaign
IEEE - HKN

**Comment by hakantekgul** [comment]
I can not join the google groups. Please help!!

**Comment by abrahamchan** [comment]
Hi Hakan,

Thanks for using LLFI. 
Have you tried to specify the JAVA_HOME_DIR explicitly in the ./setup command?

**Comment by hakantekgul** [comment]
I tried that right now. I tried the setup command below with the following arguments. This may fix the java_home issue but I get the error where LLFI build directory exists as below. I could not locate and delete the build directory. Can you please help? I am very new to these kinds of things. Thanks!

./setup -LLFI_BUILD_ROOT ~/Desktop/LLFI -LLVM_SRC_ROOT ~/Desktop/LLFI/llvmsrc -LLVM_DST_ROOT ~/Desktop/LLFI/llvm -JAVA_HOME_DIR /Library/Java/JavaVirtualMachines/jdk1.8.0_131.jdk/Contents/Home/

ERROR: LLFI build directory already exists!

**Comment by karthikp-ubc** [comment]
I think this should be posted to llfi-development as it pertains to a specific installation issue rather than a generic issue with LLFI. Please provide as much context as possible in that post. Thanks.

I'm closing this issue now.
