### ISSUE TITLE
Error with using customRegSelector

### ISSUE THREAD

**Issue by saber1994** [DependableSystemsLab/LLFI#112]
I want to use a customRegSelector and I faced a error when running command "instrument":
My input.yaml is below:

    compileOption:
       instSelMethod:
         - customInstselector:
              include:
                - onlymain         
      regSelMethod: customregselector
      customRegSelector: onlyconstint

      includeInjectionTrace: 
        - forward
        - backward

      tracingPropagation: True # trace dynamic instruction values.

      tracingPropagationOption:
        maxTrace: 250 # max number of instructions to trace during fault injection run
        debugTrace: True/False
        generateCDFG: True

     runOption:
        - run:
           numOfRuns: 3
           fi_type: bitflip

The error message is below:

Invalid indices for GEP pointer type!
  %74 = getelementptr %struct.OptionData_* %73, i32 %fi28, i32 %fi29, !llfi_index !100
Invalid indices for GEP pointer type!
  %79 = getelementptr %struct.OptionData_* %78, i32 %fi30, i32 %fi31, !llfi_index !105
Invalid indices for GEP pointer type!
  %84 = getelementptr %struct.OptionData_* %83, i32 %fi32, i32 %fi33, !llfi_index !110
Invalid indices for GEP pointer type!
  %89 = getelementptr %struct.OptionData_* %88, i32 %fi34, i32 %fi35, !llfi_index !115
Invalid indices for GEP pointer type!
  %94 = getelementptr %struct.OptionData_* %93, i32 %fi36, i32 %fi37, !llfi_index !120
Invalid indices for GEP pointer type!
  %99 = getelementptr %struct.OptionData_* %98, i32 %fi38, i32 %fi39, !llfi_index !125
Invalid indices for GEP pointer type!
  %104 = getelementptr %struct.OptionData_* %103, i32 %fi40, i32 %fi41, !llfi_index !130
Invalid indices for GEP pointer type!
  %109 = getelementptr %struct.OptionData_* %108, i32 %fi42, i32 %fi43, !llfi_index !135
Invalid indices for GEP pointer type!
  %114 = getelementptr %struct.OptionData_* %113, i32 %fi44, i32 %fi45, !llfi_index !140
Invalid indices for GEP pointer type!
  %187 = getelementptr %struct.OptionData_* %186, i32 %fi61, i32 %fi62, !llfi_index !227
Invalid indices for GEP pointer type!
  %200 = getelementptr %struct.OptionData_* %199, i32 %fi66, i32 %fi67, !llfi_index !241
Invalid indices for GEP pointer type!
  %210 = getelementptr %struct.OptionData_* %209, i32 %fi68, i32 %fi69, !llfi_index !252
Invalid indices for GEP pointer type!
  %220 = getelementptr %struct.OptionData_* %219, i32 %fi70, i32 %fi71, !llfi_index !263
Invalid indices for GEP pointer type!
  %230 = getelementptr %struct.OptionData_* %229, i32 %fi72, i32 %fi73, !llfi_index !274
Invalid indices for GEP pointer type!
  %240 = getelementptr %struct.OptionData_* %239, i32 %fi74, i32 %fi75, !llfi_index !285
Broken module found, compilation aborted!
0  opt             0x0000000001203ba2 llvm::sys::PrintStackTrace(_IO_FILE*) + 34
1  opt             0x000000000120343c
2  libpthread.so.0 0x00007f423cf52890
3  libc.so.6       0x00007f423c190067 gsignal + 55
4  libc.so.6       0x00007f423c191448 abort + 328
5  opt             0x000000000112297c
6  opt             0x000000000112bbe7
7  opt             0x000000000110512f llvm::FPPassManager::runOnFunction(llvm::Function&) + 623
8  opt             0x0000000001107433 llvm::legacy::PassManagerImpl::run(llvm::Module&) + 611
9  opt             0x0000000000571f18 main + 2680
10 libc.so.6       0x00007f423c17cb45 __libc_start_main + 245
11 opt             0x000000000058cf15
Stack dump:

**Comment by karthikp-ubc** [comment]
It's difficult for us to reproduce this error without further details of your setup and benchmark. Did your installation of LLFI pass the regression tests ? if not, I suggest checking that first.
