### ISSUE TITLE
"llfi.stat.prof.txt: Not Generated

### ISSUE THREAD

**Issue by ruotongyu** [DependableSystemsLab/LLFI#115]
I was trying to run cpp files but in some cases "llfi.stat.prof.txt" is not generated after profile. It this means there is no place to inject fault or I did something going wrong? Thanks for help!

**Comment by karthikp-ubc** [comment]
Can you please provide more details ? Are you getting any error messages ? Can you check if the instrumentation pass completed successfully ? It's very difficult to tell what's going on based on the content of your message ? Thanks.

**Comment by ruotongyu** [comment]
This is the output from console:
$ /home/ruotoy/Desktop/llfi/bin/instrument -lpthread --readable neural-net/neural-net.ll
/usr/bin/ld: /home/ruotoy/Desktop/llfi/bin/neural-net/llfi/neural-net-profiling.o: undefined reference to symbol '_ZStlsIcSt11char_traitsIcESaIcEERSt13basic_ostreamIT_T0_ES7_RKNSt7__cxx1112basic_stringIS4_S5_T1_EE@@GLIBCXX_3.4.21'
//usr/lib/x86_64-linux-gnu/libstdc++.so.6: error adding symbols: DSO missing from command line
clang-3.4: error: linker command failed with exit code 1 (use -v to see invocation)
/usr/bin/ld: /home/ruotoy/Desktop/llfi/bin/neural-net/llfi/neural-net-faultinjection.o: undefined reference to symbol '_ZStlsIcSt11char_traitsIcESaIcEERSt13basic_ostreamIT_T0_ES7_RKNSt7__cxx1112basic_stringIS4_S5_T1_EE@@GLIBCXX_3.4.21'
//usr/lib/x86_64-linux-gnu/libstdc++.so.6: error adding symbols: DSO missing from command line
clang-3.4: error: linker command failed with exit code 1 (use -v to see invocation)
Success
Change directory to: /home/ruotoy/Desktop/llfi/bin/neural-net
...Error compiling with clang, trying with clang++.
...Error compiling with clang, trying clang++.

According to the output, I am not sure if the instrumentation pass completed successfully. 
I am running LLFI on Ubuntu 16.04 which seems do not support clang-3.4. Will this cause the error "clang-3.4: error: linker command failed with exit code 1 (use -v to see invocation)" ?

**Comment by ruotongyu** [comment]
I tested on several cpp programs. The console outputs are same as I posed above. However, some of the programs are good to profile but the one I mentioned are not. It does not generate "llfi.stat.prof.txt" file after profiling.

**Comment by karthikp-ubc** [comment]
Sorry, but at this time, we don't support multiple module compilation with C++. Looks like there's a linker error when you try to compile the program with LLFI instrumentation on, and that's why it's failing.
