### ISSUE TITLE
Fail to Instrument cpp files

### ISSUE THREAD

**Issue by ruotongyu** [DependableSystemsLab/LLFI#116]
@karthikp-ubc 
Hello Karthikp, 
I am also trying to use LLFI to inject faults to cpp projects. However, it always report error "error: expected top-level entity" when I try to do instrument. 

_/home/ruotoy/Desktop/llvm/bin/llvm-link: main.ll:81:1: error: expected top-level entity
$_ZStorSt13_Ios_OpenmodeS_ = comdat any_

It looks fine when I compile the project. I do not know if this error comes from the version of clang and llvm?
Really appreciate your help!!

**Comment by ruotongyu** [comment]
This error only happens when I try to compile cpp file which include header files. I am not sure if I did something wrong to link several files together.

**Comment by karthikp-ubc** [comment]
Sorry, this looks like an LLVm issue and not an LLFI issue, so we cant help with it unfortunately.
