### ISSUE TITLE
Python Autoinstaller deprecated library

### ISSUE THREAD

**Issue by jamilgafur** [DependableSystemsLab/LLFI#130]
One of the python packages (imp) has been deprecated for python;

"Deprecated since version 3.4: The [imp](https://docs.python.org/3/library/imp.html#module-imp) module is deprecated in favor of [importlib](https://docs.python.org/3/library/importlib.html#module-importlib)."

https://docs.python.org/3/library/imp.html#:~:text=Deprecated%20since%20version%203.4%3A%20The,deprecated%20in%20favor%20of%20importlib%20.&text=Return%20the%20magic%20string%20value,different%20for%20each%20Python%20version.)

**Comment by uditagarwal97** [comment]
Hi @jamilgafur,
Thanks for bringing this up. LLFI is now depreciated and we have moved the entire LLFI codebase to a new project LLTFI (https://github.com/DependableSystemsLab/LLTFI). LLTFI works with the latest version of LLVM and we have upgraded all the package dependencies as well.
