### ISSUE TITLE
Executing fault injection in 32-bit linux system

### ISSUE THREAD

**Issue by nithya11** [DependableSystemsLab/LLFI#25]
When fault injection is performed the llfi.stat files are not generated and it results as follows: (This occurs only for 32-bit system and works fine for 64-bit)

factorial-faultinjection.exe: /home/nithyan/Installer-Package/llfisrc/runtime_lib/FaultInjectionLib.c:135: preFunc: Assertion `opcodecyclearray[opcode] >= 0 && "opcode does not exist, need to update instructions.def"' failed.

Kernel: Forcing run

Run fault injection executable with default timeout 500

======Fault Injection======

---FI Config #0---

[>--------------------------------------------------] 0.0% (0 / 2) factorial-faultinjection.exe: /home/nithyan/Installer-Package/llfisrc/runtime_lib/FaultInjectionLib.c:135: preFunc: Assertion `opcodecyclearray[opcode] >= 0 && "opcode does not exist, need to update instructions.def"' failed.

[=========================>-------------------------] 50.0% (1 / 2) 

[==================================================>] 100.0% (2 / 2)

**Comment by karthikp-ubc** [comment]
We no longer support 32 bit systems, so I'm closing this issue. Feel free to reopen if needed.
