### ISSUE TITLE
Manual Installation

### ISSUE THREAD

**Issue by flyree** [DependableSystemsLab/LLFI#52]
Hi all,

I was trying to follow the instructions for manual install, but when I run ./setup, I got an error message that python must be in version 3. But on the webpage, it says python 2.7 and above. If I change the python in setup to 2, I always got this message:
File "./setup", line 44
    print(msg, file=sys.stderr)
                   ^
SyntaxError: invalid syntax

This is not consistent. Another question, why limit the user to use Python 3? 

Bo

**Comment by karthikp-ubc** [comment]
Upgraded support to Python3. Python2x is deprecated.
