### ISSUE TITLE
What's the difference between the various source registers

### ISSUE THREAD

**Issue by timahfika** [DependableSystemsLab/LLFI#54]
This is not an issue report... Just wanted to know what's the difference between injecting in the different source registers i.e srcreg1, srcreg2, srcreg3 and srcreg4?

**Comment by jshwei** [comment]
They are what the name says, srcreg1 is injecting into the first register of the selected instruction, and srcreg2 is injecting into the second register. say it's a store instruction, srcreg1 is to inject into the data, while srcreg2 is to inject into the address
