### ISSUE TITLE
How I can generate a single .ll file out of c sources and header files?

### ISSUE THREAD

**Issue by andrestoga** [DependableSystemsLab/LLFI#74]
Hi,

I used the LLFI GUI tool to generate a trace graph but the problem is that when I load the files of my project it generates a makefile to create multiples .ll files instead of a single one.

Do I have to use the command line tool "GenerateMakefile" to create a make file for a single .ll file? and if so, how I can do that?

Best,

**Comment by karthikp-ubc** [comment]
Sorry for the late response. Please post this to the LLFI development group so other can answer (you can find the address on the home page). Thanks,

- Karthik
