### ISSUE TITLE
I can't compile OpenMP programs

### ISSUE THREAD

**Issue by andrestoga** [DependableSystemsLab/LLFI#75]
Hi,

I'm using the GUI tool to generate a trace graph but the problem is that I'm getting and error when I tried to instrument the file. This is the error:

/home/llfi/Desktop/llfi/bin/Testing/llfi/Testing-profiling.ll:(.text+0xb4f): undefined reference to `omp_set_num_threads'

I also tried with a hello world openMP example but it didn't even pass the "Compile To IR" stage. This is the error:

openmp_simple.c:3:10: fatal error: 'omp.h' file not found
#include "omp.h"
         ^
1 error generated.
make: *** [openmp_simple.ll] Error 1

Can you help me please?

Best,

**Comment by karthikp-ubc** [comment]
Again, please post this to the llfi-development group as it's not really an issue with LLFI per se. Thanks,

- Karthik
