### ISSUE TITLE
I can't find the LLFI development group, sorry for post it here again

### ISSUE THREAD

**Issue by andrestoga** [DependableSystemsLab/LLFI#77]
Hi,

Sorry for posting it here but I didn't find the LLFI development group and I don't know other way of communication other than this. In the home page it says:

"Please join the following Google Groups for information related to LLFI development: llfi-development@googlegroups.com"

But it is just an email address which throws an error whenever I send an email. I also searched on the internet the google group but I didn't find it. I just found the LLVM development group. Is that the group?

Best,

**Comment by karthikp-ubc** [comment]
I just sent you an invitation to the LLFI development group to your gmail address. Let me know if you didn't get it. Thanks,

- karthik
