### ISSUE TITLE
help in llfi

### ISSUE THREAD

**Issue by 1Husin-Alhaj** [DependableSystemsLab/LLFI#78]
hi
After many attempts, I have not yet found the right way to install LLFI
I am very confused and very sad because after 3 days of reading and trying to install llfi (also llvm and another external packages), the terminal ansower was always  (ERROR , ERROR , ERROR :( ) .
below is a picture which explains the problem

can you help me, please

Running ./setup for LLFI:
ERROR: You need to install Python Yaml module before building LLFI.

Please fix the above error(s) before building LLFI.

// I installed python and python yaml
but still the error appears .

with regards

**Comment by hakantekgul** [comment]
Hello, I have the same problem in Mac. Please help!

**Comment by karthikp-ubc** [comment]
Please join llfi-development list and post it there. This is not the appropriate forum for posting installation questions. Thanks,

**Comment by Ram7799** [comment]
Im having the same error. Please add me to the google groups
