### ISSUE TITLE
can I use LLFI to inject CFE (control-flow error) into the code 

### ISSUE THREAD

**Issue by 1Husin-Alhaj** [DependableSystemsLab/LLFI#80]
CFE control-flow error is a violation program's control during run-time
llfi is a fault injection tool , but can llfi make a control- flow error , or not , 
like modify the value of stack pointer or (%eip instruction pointer register) and how, or not.
thanks

**Comment by flyree** [comment]
Generally LLFI works on LLVM IR level, which means that you don't have much access to lower level information. But in your case, getelementptr is the instruction you may want to take a look. I think the DSN paper has some discussion about it.

**Comment by 1Husin-Alhaj** [comment]
I'd like to thank you for your answer Mr "flyree". 
excuseme, the DSN paper you suggested , where I can find it ? Are you have a link for it.

**Comment by flyree** [comment]
On the LLFI main page.
