### ISSUE TITLE
If i have finish the installing?because at the end of trace,it's no successful prompt

### ISSUE THREAD

**Issue by lidanfeng** [DependableSystemsLab/LLFI#82]
Scanning dependencies of target test_suite-SCRIPTS
[ 72%] Generating build_prog.py
[ 72%] Generating check_injection.py
[ 73%] Generating clean_prog.py
[ 74%] Generating clear_all.py
[ 74%] Generating clear_llfi.py
[ 75%] Generating deploy_prog.py
[ 76%] Generating inject_prog.py
[ 77%] Generating test_trace_tools.py
[ 77%] Generating llfi_test
[ 78%] Generating test_generate_makefile.py
[ 78%] Built target test_suite-SCRIPTS
Scanning dependencies of target gui
[ 79%] Generating application/ClosePopupController.class
[ 79%] Generating application/CompileToIrController.class
×¢: /mnt/llfi/llfisrc/gui/application/Controller.javaÊ¹ÓÃÁËÎ´¾­¼ì²é»ò²»°²È«µÄ²Ù×÷¡£
×¢: ÓÐ¹ØÏêÏ¸ÐÅÏ¢, ÇëÊ¹ÓÃ -Xlint:unchecked ÖØÐÂ±àÒë¡£
[ 80%] Generating application/FaultInjectionController.class
×¢: /mnt/llfi/llfisrc/gui/application/Controller.javaÊ¹ÓÃÁËÎ´¾­¼ì²é»ò²»°²È«µÄ²Ù×÷¡£
×¢: ÓÐ¹ØÏêÏ¸ÐÅÏ¢, ÇëÊ¹ÓÃ -Xlint:unchecked ÖØÐÂ±àÒë¡£
[ 80%] Generating application/Main.class
[ 81%] Generating application/MyThread.class
×¢: /mnt/llfi/llfisrc/gui/application/Controller.javaÊ¹ÓÃÁËÎ´¾­¼ì²é»ò²»°²È«µÄ²Ù×÷¡£
×¢: ÓÐ¹ØÏêÏ¸ÐÅÏ¢, ÇëÊ¹ÓÃ -Xlint:unchecked ÖØÐÂ±àÒë¡£
[ 82%] Generating application/ProfilingController.class
×¢: /mnt/llfi/llfisrc/gui/application/Controller.javaÊ¹ÓÃÁËÎ´¾­¼ì²é»ò²»°²È«µÄ²Ù×÷¡£
×¢: ÓÐ¹ØÏêÏ¸ÐÅÏ¢, ÇëÊ¹ÓÃ -Xlint:unchecked ÖØÐÂ±àÒë¡£
[ 82%] Generating application/ProgressBarController.class
×¢: /mnt/llfi/llfisrc/gui/application/Controller.javaÊ¹ÓÃÁËÎ´¾­¼ì²é»ò²»°²È«µÄ²Ù×÷¡£
×¢: ÓÐ¹ØÏêÏ¸ÐÅÏ¢, ÇëÊ¹ÓÃ -Xlint:unchecked ÖØÐÂ±àÒë¡£
[ 83%] Generating application/SaveProfileController.class
×¢: /mnt/llfi/llfisrc/gui/application/Controller.javaÊ¹ÓÃÁËÎ´¾­¼ì²é»ò²»°²È«µÄ²Ù×÷¡£
×¢: ÓÐ¹ØÏêÏ¸ÐÅÏ¢, ÇëÊ¹ÓÃ -Xlint:unchecked ÖØÐÂ±àÒë¡£
[ 83%] Generating application/TraceController.class
×¢: /mnt/llfi/llfisrc/gui/application/Controller.javaÊ¹ÓÃÁËÎ´¾­¼ì²é»ò²»°²È«µÄ²Ù×÷¡£
×¢: ÓÐ¹ØÏêÏ¸ÐÅÏ¢, ÇëÊ¹ÓÃ -Xlint:unchecked ÖØÐÂ±àÒë¡£
[ 84%] Generating application/TraceOpenError.fxml
[ 84%] Generating application/TracingErrorDisplay.fxml
[ 85%] Generating application/compileToIR.fxml
[ 86%] Generating application/Config.fxml
[ 86%] Generating application/ErrorDisplay.fxml
[ 87%] Generating application/InjectFaultResult.fxml
[ 88%] Generating application/Instrument.fxml
[ 89%] Generating application/NextRunOptionPopup.fxml
[ 89%] Generating application/Profile.fxml
[ 90%] Generating application/ProfileName.fxml
[ 91%] Generating application/ProfileWithInput.fxml
[ 91%] Generating application/Profiling.fxml
[ 92%] Generating application/ProgressWindow.fxml
[ 93%] Generating application/Sample.fxml
[ 94%] Generating gui_config.yaml
[ 94%] Generating application/lib/snakeyaml-1.15.jar
[100%] Built target gui
running install
running build
running build_py
copying lib3/yaml/serializer.py -> build/lib.linux-x86_64-3.2/yaml
copying lib3/yaml/reader.py -> build/lib.linux-x86_64-3.2/yaml
copying lib3/yaml/composer.py -> build/lib.linux-x86_64-3.2/yaml
copying lib3/yaml/representer.py -> build/lib.linux-x86_64-3.2/yaml
copying lib3/yaml/loader.py -> build/lib.linux-x86_64-3.2/yaml
copying lib3/yaml/nodes.py -> build/lib.linux-x86_64-3.2/yaml
copying lib3/yaml/__init__.py -> build/lib.linux-x86_64-3.2/yaml
copying lib3/yaml/constructor.py -> build/lib.linux-x86_64-3.2/yaml
copying lib3/yaml/error.py -> build/lib.linux-x86_64-3.2/yaml
copying lib3/yaml/resolver.py -> build/lib.linux-x86_64-3.2/yaml
copying lib3/yaml/cyaml.py -> build/lib.linux-x86_64-3.2/yaml
copying lib3/yaml/events.py -> build/lib.linux-x86_64-3.2/yaml
copying lib3/yaml/parser.py -> build/lib.linux-x86_64-3.2/yaml
copying lib3/yaml/dumper.py -> build/lib.linux-x86_64-3.2/yaml
copying lib3/yaml/tokens.py -> build/lib.linux-x86_64-3.2/yaml
copying lib3/yaml/emitter.py -> build/lib.linux-x86_64-3.2/yaml
copying lib3/yaml/scanner.py -> build/lib.linux-x86_64-3.2/yaml
running build_ext
running install_lib
creating /mnt/llfi/pyyaml
creating /mnt/llfi/pyyaml/lib
creating /mnt/llfi/pyyaml/lib/python3.2
creating /mnt/llfi/pyyaml/lib/python3.2/site-packages
creating /mnt/llfi/pyyaml/lib/python3.2/site-packages/yaml
copying build/lib.linux-x86_64-3.2/yaml/serializer.py -> /mnt/llfi/pyyaml/lib/python3.2/site-packages/yaml
copying build/lib.linux-x86_64-3.2/yaml/reader.py -> /mnt/llfi/pyyaml/lib/python3.2/site-packages/yaml
copying build/lib.linux-x86_64-3.2/yaml/composer.py -> /mnt/llfi/pyyaml/lib/python3.2/site-packages/yaml
copying build/lib.linux-x86_64-3.2/yaml/representer.py -> /mnt/llfi/pyyaml/lib/python3.2/site-packages/yaml
copying build/lib.linux-x86_64-3.2/yaml/loader.py -> /mnt/llfi/pyyaml/lib/python3.2/site-packages/yaml
copying build/lib.linux-x86_64-3.2/yaml/nodes.py -> /mnt/llfi/pyyaml/lib/python3.2/site-packages/yaml
copying build/lib.linux-x86_64-3.2/yaml/__init__.py -> /mnt/llfi/pyyaml/lib/python3.2/site-packages/yaml
copying build/lib.linux-x86_64-3.2/yaml/constructor.py -> /mnt/llfi/pyyaml/lib/python3.2/site-packages/yaml
copying build/lib.linux-x86_64-3.2/yaml/error.py -> /mnt/llfi/pyyaml/lib/python3.2/site-packages/yaml
copying build/lib.linux-x86_64-3.2/yaml/resolver.py -> /mnt/llfi/pyyaml/lib/python3.2/site-packages/yaml
copying build/lib.linux-x86_64-3.2/yaml/cyaml.py -> /mnt/llfi/pyyaml/lib/python3.2/site-packages/yaml
copying build/lib.linux-x86_64-3.2/yaml/events.py -> /mnt/llfi/pyyaml/lib/python3.2/site-packages/yaml
copying build/lib.linux-x86_64-3.2/yaml/parser.py -> /mnt/llfi/pyyaml/lib/python3.2/site-packages/yaml
copying build/lib.linux-x86_64-3.2/yaml/dumper.py -> /mnt/llfi/pyyaml/lib/python3.2/site-packages/yaml
copying build/lib.linux-x86_64-3.2/yaml/tokens.py -> /mnt/llfi/pyyaml/lib/python3.2/site-packages/yaml
copying build/lib.linux-x86_64-3.2/yaml/emitter.py -> /mnt/llfi/pyyaml/lib/python3.2/site-packages/yaml
copying build/lib.linux-x86_64-3.2/yaml/scanner.py -> /mnt/llfi/pyyaml/lib/python3.2/site-packages/yaml
byte-compiling /mnt/llfi/pyyaml/lib/python3.2/site-packages/yaml/serializer.py to serializer.cpython-32.pyc
byte-compiling /mnt/llfi/pyyaml/lib/python3.2/site-packages/yaml/reader.py to reader.cpython-32.pyc
byte-compiling /mnt/llfi/pyyaml/lib/python3.2/site-packages/yaml/composer.py to composer.cpython-32.pyc
byte-compiling /mnt/llfi/pyyaml/lib/python3.2/site-packages/yaml/representer.py to representer.cpython-32.pyc
byte-compiling /mnt/llfi/pyyaml/lib/python3.2/site-packages/yaml/loader.py to loader.cpython-32.pyc
byte-compiling /mnt/llfi/pyyaml/lib/python3.2/site-packages/yaml/nodes.py to nodes.cpython-32.pyc
byte-compiling /mnt/llfi/pyyaml/lib/python3.2/site-packages/yaml/__init__.py to __init__.cpython-32.pyc
byte-compiling /mnt/llfi/pyyaml/lib/python3.2/site-packages/yaml/constructor.py to constructor.cpython-32.pyc
byte-compiling /mnt/llfi/pyyaml/lib/python3.2/site-packages/yaml/error.py to error.cpython-32.pyc
byte-compiling /mnt/llfi/pyyaml/lib/python3.2/site-packages/yaml/resolver.py to resolver.cpython-32.pyc
byte-compiling /mnt/llfi/pyyaml/lib/python3.2/site-packages/yaml/cyaml.py to cyaml.cpython-32.pyc
byte-compiling /mnt/llfi/pyyaml/lib/python3.2/site-packages/yaml/events.py to events.cpython-32.pyc
byte-compiling /mnt/llfi/pyyaml/lib/python3.2/site-packages/yaml/parser.py to parser.cpython-32.pyc
byte-compiling /mnt/llfi/pyyaml/lib/python3.2/site-packages/yaml/dumper.py to dumper.cpython-32.pyc
byte-compiling /mnt/llfi/pyyaml/lib/python3.2/site-packages/yaml/tokens.py to tokens.cpython-32.pyc
byte-compiling /mnt/llfi/pyyaml/lib/python3.2/site-packages/yaml/emitter.py to emitter.cpython-32.pyc
byte-compiling /mnt/llfi/pyyaml/lib/python3.2/site-packages/yaml/scanner.py to scanner.cpython-32.pyc
running install_egg_info
Writing /mnt/llfi/pyyaml/lib/python3.2/site-packages/PyYAML-3.11-py3.2.egg-info
root@SZX1000074727:/mnt/llfi# ll

**Comment by karthikp-ubc** [comment]
If you saw no error messages, the installation was successful. Try running the test suites to make sure.
