### ISSUE TITLE
It seems all the injection isn't done correctly,what's wrong with it

### ISSUE THREAD

**Issue by lidanfeng** [DependableSystemsLab/LLFI#84]
gandalf@SZX1000074727:/mnt/llfi20160324/llfi/test_suite/SCRIPTS$ python3 inject_prog.py 1 insttype
ERROR: instrument failed for: /mnt/llfi20160324/llfi/test_suite/HardwareFaults/insttype MCF.ll
ERROR: Skip: ./HardwareFaults/insttype
gandalf@SZX1000074727:/mnt/llfi20160324/llfi/test_suite/SCRIPTS$ python3 check_injection.py
=============== Result ===============
./SoftwareFaults/DataCorruption_Data             FAIL: No ./llfi folder found!
./SoftwareFaults/MemoryLeak_Res                  FAIL: No ./llfi folder found!
./SoftwareFaults/InvalidSender_MPI               FAIL: No ./llfi folder found!
./BatchMode/NoOpen_API_WrongMode_API_BufferUnderflow_API                 Subdirectories for failure modes not found!
./SoftwareFaults/BufferOverflowMalloc_Data               FAIL: No ./llfi folder found!
./SoftwareFaults/NoClose_API             FAIL: No ./llfi folder found!
./SoftwareFaults/BufferUnderflow_API             FAIL: No ./llfi folder found!
./SoftwareFaults/NoDrain_MPI             FAIL: No ./llfi folder found!
./SoftwareFaults/NoAck_MPI               FAIL: No ./llfi folder found!
./SoftwareFaults/WrongSavedFormat_IO             FAIL: No ./llfi folder found!
./HardwareFaults/funcname                FAIL: No ./llfi folder found!
./SoftwareFaults/WrongSource_Data                FAIL: No ./llfi folder found!
./SoftwareFaults/InappropriateClose_API                  FAIL: No ./llfi folder found!
./SoftwareFaults/WrongMode_API           FAIL: No ./llfi folder found!
./HardwareFaults/insttype                FAIL: No ./llfi folder found!
./SoftwareFaults/CPUHog_Res              FAIL: No ./llfi folder found!
./SoftwareFaults/IncorrectOutput_Data            FAIL: No ./llfi folder found!
./SoftwareFaults/PacketStorm_MPI                 FAIL: No ./llfi folder found!
./SoftwareFaults/NoMessage_MPI           FAIL: No ./llfi folder found!
./SoftwareFaults/WrongPointer_Data               FAIL: No ./llfi folder found!
./SoftwareFaults/BufferOverflow_API              FAIL: No ./llfi folder found!
./SoftwareFaults/MemoryExhaustion_Res            FAIL: No ./llfi folder found!
./SoftwareFaults/NoOutput_API            FAIL: No ./llfi folder found!
./SoftwareFaults/RaceCondition_Timing            FAIL: No ./llfi folder found!
./SoftwareFaults/UnderAccumulator_Res            FAIL: No ./llfi folder found!
./SoftwareFaults/IncorrectOutput_API             FAIL: No ./llfi folder found!
./SoftwareFaults/NoOutput_Data           FAIL: No ./llfi folder found!
./HardwareFaults/llfiindex               FAIL: No ./llfi folder found!
./HardwareFaults/multiplebits            FAIL: No ./llfi folder found!
./SoftwareFaults/WrongDestination_Data           FAIL: No ./llfi folder found!
./SoftwareFaults/NoOpen_API              FAIL: No ./llfi folder found!
./SoftwareFaults/InvalidMessage_MPI              FAIL: No ./llfi folder found!
./SoftwareFaults/HighFrequentEvent_Timing                FAIL: No ./llfi folder found!
./SoftwareFaults/ThreadKiller_Res                FAIL: No ./llfi folder found!
./BatchMode/SoftwareFailureAutoScan              Subdirectories for failure modes not found!
./SoftwareFaults/InvalidPointer_Res              FAIL: No ./llfi folder found!
./SoftwareFaults/BufferOverflowMemmove_Data              FAIL: No ./llfi folder found!
./HardwareFaults/tracing                 FAIL: No ./llfi folder found!
./SoftwareFaults/LowMemory_Res           FAIL: No ./llfi folder found!
./HardwareFaults/random                  FAIL: No ./llfi folder found!
./SoftwareFaults/Deadlock_Res            FAIL: No ./llfi folder found!
./SoftwareFaults/WrongRetrievedFormat_IO                 FAIL: No ./llfi folder found!
./SoftwareFaults/StalePointer_Res                FAIL: No ./llfi folder found!
./SoftwareFaults/WrongAPI_API            FAIL: No ./llfi folder found!
./SoftwareFaults/WrongRetrievedAddress_IO                FAIL: No ./llfi folder found!
./SoftwareFaults/WrongSavedAddress_IO            FAIL: No ./llfi folder found!
gandalf@SZX1000074727:/mnt/llfi20160324/llfi/test_suite/SCRIPTS$

**Comment by karthikp-ubc** [comment]
Your installation is not done correctly. I'm not sure what's going on - it seems like the main LLFI folder is not getting created. Please double check your installation.

- Karthik
