### ISSUE TITLE
the method of link library when excute the command insturment is only support one kinds of GCC,we need more kinds of  GCC method

### ISSUE THREAD

**Issue by lidanfeng** [DependableSystemsLab/LLFI#94]
the method of link library when excute the command insturment is only support one kinds of GCC,we need more kinds of  GCC link library method

**Comment by karthikp-ubc** [comment]
I don't understand the issue. Can you please be more specific ? Also, it seems like an LLVM issue to me, not an LLFI issue. This is not the right forum to post LLVM issues unfortunately, so I'm closing it. Thanks,
