### ISSUE TITLE
when I try to inject data corruption fault,there is a error

### ISSUE THREAD

**Issue by lidanfeng** [DependableSystemsLab/LLFI#95]
1 ,we compile a number of  .c file to .bc separately
2 We link all the .bc files to a big .bc file .
3 We execute the instrument script to inject fault ,but there is no compile parameter to include head file.
When we use  gcc, we must use compile parameter to include head file.  gcc main.c -lm -I ./Test/include -L ./Test/lib  -lmyfac -o a.out

I notice that this error happens when I try to inject data corruption fault. While I manage to inject “NoOutput(API)” fault, no error observed.  I guess the tested program use some variable type not supported by LLFI yet.

**Comment by karthikp-ubc** [comment]
Again, we need a reproducible test case to debug this issue. With the above description, we cannot debug it. Thanks,

- karthik
