### ISSUE TITLE
 when we do batch profiling to the example factorial

### ISSUE THREAD

**Issue by lidanfeng** [DependableSystemsLab/LLFI#97]
root@SZX1000078840:/lidanfeng/llfi/bin# ./batchProfile /lidanfeng/llfi/bin/factorial/factorial.ll
factorial.ll

Run profiling command: /lidanfeng/llfi/bin/profile ./llfi/factorial-profiling.exe
profiling: CPUHog(Res)  failed!
factorial.ll

Run profiling command: /lidanfeng/llfi/bin/profile ./llfi/factorial-profiling.exe
profiling: DataCorruption(Data)  failed!
factorial.ll

Run profiling command: /lidanfeng/llfi/bin/profile ./llfi/factorial-profiling.exe
profiling: HighFrequentEvent(Timing)  failed!
factorial.ll

Run profiling command: /lidanfeng/llfi/bin/profile ./llfi/factorial-profiling.exe
profiling: IncorrectOutput(API)  failed!
factorial.ll

Run profiling command: /lidanfeng/llfi/bin/profile ./llfi/factorial-profiling.exe
profiling: NoOutput(API)  failed!
root@SZX1000078840:/lidanfeng/llfi/bin#

**Comment by MaryamRA** [comment]
Software fault models need to be injected in applicable test programs. factorial.ll is a small program that is tested by hardware fault models. It does not include any method calls that are required for the above mentioned fault models such as CPUHog(Res), HighFrequentEvent(Timing),  IncorrectOutput(API), NoOutput(API),...
In addition DataCorruption(Data) and many other software fault models are injected into called instructions of LLVM like open, read, memcpy, malloc,...and this kind of instructions do not exist in factorial program.
