### ISSUE TITLE
When we execute batchInstrument, there is an error. 

### ISSUE THREAD

**Issue by lidanfeng** [DependableSystemsLab/LLFI#99]
When we execute batchInstrument, there is an error.
The directory “/mnt/tools/llfi/bin/factorial” is havenothing to do with  we are choosen to inject failure

root@SZX1000079191:/mnt/tools/llfi/bin# ./batchInstrument --readable /mnt/tools/llfi/Src/br_FusionStorage_V1R3C30_Update/Src/dsware/build/dsware_osd.bc
ERROR: Unable to copy: /mnt/tools/llfi/bin/factorial
to: /mnt/tools/llfi/bin/llfi-DataCorruption(Data)
root@SZX1000079191:/mnt/tools/llfi/bin#

**Comment by karthikp-ubc** [comment]
Please provide more details, including the steps you took to reproduce this bug. Also, do you have permissions to write to mnt/tools ? Thanks,

- karthik
